// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

// Import the verifier generated by hardhat-noir
import {HonkVerifier as ValidMoveVerifier} from "../noir/target/valid_move.sol";

contract ValidMoveTest {
    ValidMoveVerifier public verifier;

    constructor() {
        verifier = new ValidMoveVerifier();
    }

    /// @notice Verify a valid_move proof
    /// @param proof The ZK proof bytes
    /// @param publicInputs All public inputs flattened
    function verifyMove(
        bytes calldata proof,
        bytes32[] calldata publicInputs
    ) external view returns (bool) {
        return verifier.verify(proof, publicInputs);
    }
}
